### ISSUE TITLE
Grade buildsystem

### ISSUE THREAD

**Issue by Danm72** [QuantumBadger/RedReader#129]
Perhaps migrating to gradle would benefit this project, proguard and signing as well as dependencies are some benefits I'd name offhand. 
I could look into this if there's any interest?

**Comment by mvdan** [comment]
Hey @QuantumBadger, don't know if you remember me but I'm one of the people behind F-Droid. I added your app way back when you posted about it on reddit :)

I recently had a try at porting RedReader to gradle. Some comments:

* We support gradle, it would work just as fine as mavne
* Proguard support - be it with gradle or with maven - is critical, the apk size is getting a bit too large
* The deps would work the same with gradle, since it uses maven repos too
* Unfortunately, what kept me from doing a PR for gradle support (everything else was working) was that holoeverywhere is an old library and is only published in apklib format, not the newer format aar. Gradle doesn't support apklib.
* Don't know about IntelliJ, but you could use Android Studio with the gradle setup.

Some extra comments that could apply to maven:
* Please look into using a higher targetSdk, both in pom.xml and in AndroidManifest.xml. Keeping an old version on purpose is a bad idea.
* When was the last time you updated the versions of the libs you are using? IIRC at least two of them have updates available. Granted that newer isn't always better, but it generally is :)

**Comment by QuantumBadger** [comment]
Hi! Yes, I remember.

I'm looking to get rid of HoloEverywhere at some point (and render most of the interface with OpenGL). So it'll probably be possible to switch at some point.

As far as Proguard goes, I think the majority of the APK size is taken up with assets, particularly due to HoloEverywhere. The code

**Comment by mvdan** [comment]
Interface with OpenGL? Wouldn't that be worse than native?

Hmm, 3MB of assets sounds like a lot :)

Right, I was just wondering whether you knew that you were using an old target SDK.

**Comment by mvdan** [comment]
Oh, and regarding gradle - if you got rid of holoeverywhere, I can do a PR adding support for Gradle. We can in theory keep both maven and gradle support at once. Although you'll have duplicated stuff both in pom.xml and build.gradle: target sdk, libraries, ...

**Comment by QuantumBadger** [comment]
> Interface with OpenGL? Wouldn't that be worse than native?

My main focus is replacing the ListViews with something hand-made. Adding items/animating the horizontal swipes/etc works really badly with the native ListView. I'm also planning on replacing the native action bars, partially since Android forces one per activity, whereas I'd like one per fragment, and partially so the app can abandon HoloEverywhere (while looking mostly the same as it does now).

> We can in theory keep both maven and gradle support at once.

I'm more than happy to abandon Maven entirely when the time comes :)

**Comment by andrewgiang** [comment]
@QuantumBadger 
>My main focus is replacing the ListViews with something hand-made. Adding items/animating the horizontal swipes/etc works really badly with the native ListView. I'm also planning on replacing the native action bars, partially since Android forces one per activity, whereas I'd like one per fragment, and partially so the app can abandon HoloEverywhere (while looking mostly the same as it does now).

Consider using the [RecyclerView](https://developer.android.com/training/material/lists-cards.html) for the replacement for ListView's. Adding animations and layout configurations are separated from the RecyclerView which makes it easy for pluggable extensions [(one example)](https://github.com/ismoli/DynamicRecyclerView) for the view.

Also the actionbar can now be placed within the layout files using the [Toolbar widget](http://developer.android.com/reference/android/widget/Toolbar.html).

**Comment by QuantumBadger** [comment]
Thanks for the suggestions Andrew. I'll look into those a bit more as that could save some work. Although I already have a mostly-implemented custom listview in a local branch, which does a few things the RecyclerView doesn't (e.g. rendering and layout in a separate thread).

**Comment by genkimarshall** [comment]
Sincerely hope I'm not bothering you by bringing this up again, but I thought I'd ask if there was any follow-up in the works for this yet? I was hoping to try to contribute to RedReader, and historically have only used Gradle and Android Studio. I saw mentions of a UI rewrite soon, and was wondering if that was a move to remove HoloEverywhere as well. In which case perhaps a switch to Gradle (and potentially Android Studio?) is coming soon, and so I would wait on that. Else, I'll go ahead and set up with the current build instructions.
Again, hope not to bother, and no rush, as I'm aware this is probably not an urgent objective. :)

**Comment by QuantumBadger** [comment]
[I've just removed HoloEverywhere](https://github.com/QuantumBadger/RedReader/commit/56239a8dd121f6935e1fff51806c8212cee54d70) :)

@mvdan -- please feel free to go ahead with the gradle pull request. I'm happy to ditch Maven entirely, so no need to keep support for both.

**Comment by mvdan** [comment]
Cool! I lost my clone and my gradle changes, but I'll do them again and be back with a PR soon.

**Comment by mvdan** [comment]
I haven't forgotten about this yet :)
