### ISSUE TITLE
SPDY support

### ISSUE THREAD

**Issue by benwa** [QuantumBadger/RedReader#193]
Since Reddit supports SPDY, why not a client?  It should be noticeably faster on both mobile data and wireless.
This can be done with [koush/ion](https://github.com/koush/ion) or [square/okhttp](https://github.com/square/okhttp) (ion looks a better for this case).  What do you think?

**Comment by QuantumBadger** [comment]
Thanks for the suggestion! This would be a fairly big change, and I'm not convinced there would be much of a speed improvement.

**Comment by benwa** [comment]
A big change indeed!  I know zero Java, though from other developers, I've heard ion is very easy to drop in.
As for speed improvement, [Google's mobile test](https://developers.google.com/speed/articles/spdy-for-mobile) actually have used reddit and imgur, though they didn't expand or provide all of their findings for download.

**Comment by QuantumBadger** [comment]
The tests are for web pages, and the gains come from the loading of resources (images, CSS, etc). I doubt there would be any performance gain when requesting a JSON document with no ancillary resources.

http://www.guypo.com/not-as-spdy-as-you-thought/

Some fairly big changes would need to be made to the cache manager, which currently uses the Apache HTTP library, to handle cookies/POST data/etc over SPDY. Minor changes may need to be made to the cookie storage in the account manager.

I'm also slightly wary about bringing in libraries [of questionable quality](https://github.com/koush/ion/issues/374) to implement proprietary, experimental protocols.

So I'd be wary of adding this even if someone submitted a pull request, due to the risk of introducing bugs. Sorry :(

**Comment by benwa** [comment]
In terms of resources, html, js, css, and json are just plain text non-binary files, so they're treated the same.  Since SPDY is faster than HTTPS (not HTTP as the article states) and Reddit's API is under HTTPS, it should still give a benefit.  SPDY isn't proprietary by the way.

However, you have convinced me it isn't worth it since it can introduce bugs and a library up to par.

**Comment by QuantumBadger** [comment]
> In terms of resources, html, js, css, and json are just plain text non-binary files

I meant in terms of parallelisation of requests:

https://developers.google.com/speed/images/spdy-mobile-waterfall-spdy.png

For downloading a single file, no matter the content, SPDY has little-to-no benefit, particularly when compared to HTTP with Keep-Alive. For downloading a web page which depends on a bunch of other files, it's supposedly a bit better under some circumstances.

**Comment by grrrrr** [comment]
Is this still needed, SPDY has been depreciated in favor of HTTP/2?

**Comment by ajs124** [comment]
> SPDY has been depreciated in favor of HTTP/2?

reddit doesn't support HTTP/2 yet afaik.

This also doesn't really change @QuantumBadger's arguments against it.

**Comment by polyzen** [comment]
I think this can be closed.
