### ISSUE TITLE
Voat support 

### ISSUE THREAD

**Issue by iliketurtlesbro** [QuantumBadger/RedReader#224]
In light of Reddit's recent decision to start actively practicing censorship on their site, I propose that RedReader add support for the reddit alternative site, Voat (https://voat.co). They appear to be a fork of the reddit codebase, so I imagine that the API would be similar. It would be nice to see RedReader allow you to sign into either Reddit or Voat, giving the user a choice of service.

**Comment by ajs124** [comment]
The voat.co codebase (as seen [here](https://github.com/voat/voat)) is completeley unrelated to reddit, except for some UI stuff.
For example, voat written in C# whereas reddit is python.

Their API isn't finished either, if I recally correctly and it's also pretty different from reddit's API.
I think they had a post about the API somewhere but I can't find it at the moment since they are practically down.

Having support for different platforms in the same app would probably also compilcate account management.

IMHO someone should fork RedReader and rename it (e.g. to VoatReader) and add voat.co support.

**Comment by resir014** [comment]
Agree with @ajs124 here.

If you *really* want to support an entirely different service, just create
a fork of RedReader that focuses on Voat support.

**Comment by QuantumBadger** [comment]
I'd happily accept a pull request for this, but I agree that the changes would have to be extensive.
