### ISSUE TITLE
RedReader crashes on login

### ISSUE THREAD

**Issue by ugurcan377** [QuantumBadger/RedReader#228]
Hi,
When i tried to login to the app it crashes and app won't open again until i delete the cache. But login appears to be successful. While i can't open the app i get the message notifications. I tried to login with both my main account and a throwaway one. Result stays the same.
I am using an LG G2 with stock ROM and my Android version is 4.2.2
Here is the log fıle  https://gist.github.com/ugurcan377/aed907de091dbfdabd60

**Comment by QuantumBadger** [comment]
Thanks for the report!

It looks like you're phone's using an unusual locale, such that `i` capitalises to `İ` rather than `I`. This is then causing a bug where the app tries to look up the enum value "HİDDEN" rather than "HIDDEN".

I'll add a fix in 1.9.0 so that the locale is ignored in PrefsUtility.java. You might be able to fix the problem temporarily by setting your phone to English and deleting the app's data.
