### ISSUE TITLE
Imgur album support: include image captions

### ISSUE THREAD

**Issue by lol768** [QuantumBadger/RedReader#242]
Using v1.9.0

This is especially important for subreddits such as /r/diy.

On a completely unrelated note:

* Would be neat if this project had an IRC channel, e.g. on freenode
* Would you accept a PR which added a preference to force *everything* to be loaded over TLS, @QuantumBadger? I'm talking about any images (links to http://<anything>), images loaded by the built-in album support, images displayed by the built-in image/gif viewer, videos loaded by the built-in video system etc? This would be similar to HTTPS Everywhere. Resources unable to be loaded over TLS, or those which redirect back to a HTTP site would trigger a confirmation prompt. This wouldn't impact the internal browser.

**Comment by QuantumBadger** [comment]
Thanks for the suggestion -- I'm planning to add this in the near future.

With regards the IRC channel, I don't think RedReader has enough users to make it viable (and I wouldn't be around most of the day due to work). It's something I'll consider though.

All imgur images/albums are currently loaded over HTTPS. I think rewriting non-imgur HTTP urls to use HTTPS could lead to a load of issues. I'd be willing to consider a (thoroughly tested) PR though :)

**Comment by QuantumBadger** [comment]
Closing the ticket as this was added a while ago :)
