### ISSUE TITLE
RedReader Crashes / Not Responding without log

### ISSUE THREAD

**Issue by DistantParadox** [QuantumBadger/RedReader#294]
Version:  RedReader Beta 1.9.3.1
Device Name:  Galaxy S6
OS:  Android Version 5.1.1

I have had several crashes / RedReader not responding, but after searching my external and internal storage, there is no `redreader_crash_log_(UUID).txt` file.  Also, I have never gotten a prompt to email the exception details directly.  If there is any more information that I could provide that may be of use, I am happy to provide.

**Comment by QuantumBadger** [comment]
Thanks for the report -- not sure why that's happening though :(

Are you familiar with adb logcat? If you could send me the logcat output next time you experience a crash I should be able to see the problem.

**Comment by DistantParadox** [comment]
Unfortunately, I'm not. Maybe I'll try aLogcat on my phone since I'm not quite sure how to reproduce it.

**Comment by QuantumBadger** [comment]
I don't think aLogcat works on recent version of Android unfortunately.

However, I think this issue has been fixed here, in v1.9.3.3:

https://github.com/QuantumBadger/RedReader/commit/fe479543852179619d1d5fdcf472d5e01da797e1

It appears that the app went into an infinite loop when the link was clicked, because RedReader was telling Android to handle it, and Android was telling RedReader to handle it, and so on.

Please let me know if you manage to reproduce this with v1.9.3.3 :)

**Comment by DistantParadox** [comment]
I haven't had a crash since the update, which prior to, I did frequently.  So it seems that this has fixed it.  Thanks, looks like you can close this issue then. :)

**Comment by QuantumBadger** [comment]
Thanks!
