### ISSUE TITLE
Cannot store images on Android 6

### ISSUE THREAD

**Issue by mvdan** [QuantumBadger/RedReader#297]
Permissions went through a makeover in Android 6. I now run cm13 (6.0), and I can no longer store images.

I can still do with opening via my web browser and manually downloading the image, but would be nice to get this fixed.

No need to paste the logcat here - it's just an `open failed: EACCESS (Permission denied)` error. You probably have to make sure to request the permission at runtime on top of declaring it in your manifest.

This should be very easy to reproduce on a 6.0 emulator. Otherwise, I can test debug builds.

**Comment by QuantumBadger** [comment]
I can sort-of reproduce this in the emulator -- the save fails, but I don't get any errors in logcat (I get a dialog saying the copy from the cache to the SD card failed).

Unfortunately fixing this won't be fun -- the permission should ideally be requested at the point when the user tries to save the image:

https://github.com/QuantumBadger/RedReader/blob/master/src/main/java/org/quantumbadger/redreader/reddit/prepared/RedditPreparedPost.java#L311

But the `requestPermissions` method gives a callback to the current activity (which for the above code can be `MainActivity`, `PostListingActivity`, `CommentListingActivity`, `ImageViewActivity`, ...), rather than to an arbitrary callback method which you provide. So it's hard to think of a way to structure this that won't lead to a tangle of code :)

Maybe the best way would be to add a method to `BaseActivity` to handle the requests (and manage the request IDs) and forward the callbacks to the relevant place:

    ((BaseActivity)activity).requestPermissionWithCallback(
            Manifest.permission.WRITE_EXTERNAL_STORAGE,
            new BaseActivity.PermissionListener() { ...})

**Comment by mvdan** [comment]
I think the idea behind using an Activity as a callback instead of a simple function is that an Activity is tied to a context and to the running UI thread. I agree that it's not easy to handle this for all the activities, though. Perhaps you could implement the logic in a helper class and simply use it from each of the activities to request the permission and handle the callback.

**Comment by QuantumBadger** [comment]
Fixed! It seems to work in the emulator, but please let me know if it's still broken for you.
