### ISSUE TITLE
Built in browser shows a blank page when opening a file download link

### ISSUE THREAD

**Issue by JonasCz** [QuantumBadger/RedReader#456]
When opening a link which leads to a file download (e.g a PDF), the built in browser (WebView) just shows a blank page. (Here's a reddit post to test: https://www.reddit.com/r/linux/comments/5xc46a/an_selinux_coloring_book/)

Maybe it could do something more useful, such as send the link to the downloads app ?

**Comment by Clubfan22** [comment]
Calling
`setDownloadListener(new DownloadListener() {
			@Override
			public void onDownloadStart(String url, String userAgent, String contentDisposition, String mimetype, long      contentLength) {
				Intent i = new Intent(Intent.ACTION_VIEW);
				i.setData(Uri.parse(url));
				getContext().startActivity(i);
			}
		});`
in [WebViewFixed.java](https://github.com/QuantumBadger/RedReader/blob/master/src/main/java/org/quantumbadger/redreader/views/WebViewFixed.java) should do the basic trick, but I think it's important to either add a dialog which informs the user that they are leaving the app or even restrict it to chosen file types due to security reasons. Especially popup-filled websites come to mind and a misclick would automatically trigger a download, which is most likely not wanted.

**Comment by QuantumBadger** [comment]
Fixed by @sarbajitsaha :)
