### ISSUE TITLE
Artifacts when loading large Images

### ISSUE THREAD

**Issue by Nutomic** [QuantumBadger/RedReader#528]
When loading any large image, there are obvious artifacts shown during loading (see screenshot). I suppose this happens because you render the image directly, in full resolution. It would be better to scale the image down before displaying it. This could be solved easily by using a library like [Glide](https://github.com/bumptech/glide), which takes care of this automatically.

![vlcsnap-2017-09-05-12h20m36s983](https://user-images.githubusercontent.com/1044450/30043806-b1514d28-9234-11e7-984d-dc1487b34700.png)

**Comment by QuantumBadger** [comment]
Thanks for the report. This is intentional -- the image does get scaled down by the app before rendering, and the checkerboard is shown in the areas which haven't finished scaling yet.

I suppose we could show a loading bar instead while the initial round of scaling is taking place, but in general I'm fine with the current behaviour.

**Comment by QuantumBadger** [comment]
Checkerboard now replaced with a plain grey background, and we also now wait until the image is read from disk before hiding the loading ring.
