### ISSUE TITLE
Cannot log in/add account

### ISSUE THREAD

**Issue by Efreak** [QuantumBadger/RedReader#534]
I have RedReader running just fine on my phone, however on my tablet I cannot log into reddit. Every single time I try, over the past two days, I get a `net::ERR_NAME_NOT_RESOLVED` error *after* I login, at the point where reddit asks me to connect and I hit accept. I am not behind any proxies, VPNs, tor, etc and my DNS server is set to 8.8.8.8 and 8.8.4.4 in my router's DHCP settings; I have tried using a DNS proxy ([Acrylic](http://mayakron.altervista.org)) on my PC and it shows no DNS errors in the log, therefore I am assuming this is an issue with the app. Actually reading posts anonymously works fine, however that doesn't allow me to post, vote, or read mail; other apps (the official reddit app) have no issues at all.

There is a recording showing the error & system/device info [here](https://bots.efreakbnc.net/efreak/redreaderfail.mp4).

Logcat is [here](https://gist.github.com/Efreak/9858472f05612762afa0f6b14e17d5c4) (there's multiple instances of this that only differ in the timestamp). Obtained via `adb logcat -d|grep 14756`.

Device info:
- Device: Nexus 7 (2013) / flo
- Android Version: 7.1.2
- LineageOS version: 14.1-20170919-NIGHTLY-flo
- The only non-default system addons are official LOS superuser and f-droid's privileged extension.

Working phone is xt1528 moto e, running stock 5.1.1.

Affected versions of app:
- RedReader 1.9.8.2.1 from [f-droid](https://f-droid.org/packages/org.quantumbadger.redreader/)
- Alpha 143 from redreader.org [fdroid repo](https://redreader.org/alpha/)

**Comment by QuantumBadger** [comment]
Thanks for the detailed report, and sorry for the delayed response.

The app uses the system WebView, and I haven't had any complaints from other users, so I'm inclined to say this is a problem with the ROM somehow.

Based on the video, it looks like it's failing to look up "reddit.com". However, since the browser was already at reddit.com moments before, it doesn't seem likely that this is a DNS error.

I'm guessing that the error message is wrong, and it's actually failing to go to `http://rr_oauth_redir`, which is the place you get redirected to after logging in. We detect the attempt to go to this URL here:

https://github.com/QuantumBadger/RedReader/blob/master/src/main/java/org/quantumbadger/redreader/activities/OAuthLoginActivity.java#L160

And that tells us that the login is completed.

I suspect that there's a bug in your ROM's implementation of the WebView, and that we're not getting the `shouldOverrideUrlLoading` callback.

May be worth reporting this upstream to LineageOS, although if there's a workaround for this I'd be happy to include it.
