### ISSUE TITLE
Strange image decoding issues

### ISSUE THREAD

**Issue by legate** [QuantumBadger/RedReader#580]
I occasionally encounter images that partially show up as a checkerboard pattern like [this](https://i.imgur.com/RD6Ipch.png) (originally from [this reddit post](https://www.reddit.com/r/TheLastAirbender/comments/7xblqd/if_japan_made_avatar/)).

It seems to only happen when using the internal image viewer (Settings > Behavior > Image Viewer > Internal viewer (OpenGL). The images appear normally when using different image viewer settings and in other apps.

Maybe this is a phone-specific issue? I'm using a Pixel 2 with Android 8.1.0.

**Comment by QuantumBadger** [comment]
Thanks, I've had a few reports of image decoding and scaling issues on Android 8, for example #553.

If you're able to email me a full logcat after reproducing the issue, I'd look through it and see if there are any errors logged (I say email rather than posting it here as it may contain personally identifying info).

**Comment by QuantumBadger** [comment]
Various changes have gone in since this was raised and it should no longer be reproducible. If you notice this again please let me know!
