### ISSUE TITLE
"all my subreddits" as startpage (instead of /hot)?

### ISSUE THREAD

**Issue by kr428** [QuantumBadger/RedReader#584]
Folks; 

apologies if I either miss something about how reddit works or this app is designed to be, but: Is there some way to make the app start up in an overview just displaying new posts in all the subreddits I subscribed? 

I don't want /hot or "all subreddits" as this is way too much information for what I need, but likewise I don't want to manually crawl through all the subscribed subreddits to see whether something's new in there... 

Thanks in advance and all the best,
Kristian

**Comment by QuantumBadger** [comment]
Thanks for the suggestion. This would be a fairly big thing to implement.

We're only allowed to make a reddit request every 2 seconds, due to the API restrictions. So if a user had 100 subscriptions, it would take at least 200 seconds to load a page like this. Alternatively, we could regularly download updates in the background (e.g. every hour).

Some thought would need to be given to how the posts would be combined. For example, the posts in `/r/news` have a lot more upvotes than, for example, `/r/linux`, but you wouldn't want to push all the Linux posts to the bottom. So maybe some sort of round-robin approach?

You'd need to keep track of which posts are "new", which could mean:

1. Posts which were never shown on the screen before
2. Posts which have never been clicked on
3. Posts which aren't hidden by the user

Number 3 is already possible -- you can configure the app to mark posts as hidden when you swipe them, and they won't be shown again. This may already be sufficient for your purposes :)

**Comment by jayhybrid** [comment]
I am also _needing_ a feature like this. Its the only reason I am using the official Reddit App (which is agony, really) please! Even if it was slow and only updated daily/weekly, I'd be so happy to see this!

**Comment by QuantumBadger** [comment]
Since this issue was raised, the Front Page was changed to combine posts from 250 of the subreddits you're subscribed to:

https://old.reddit.com/r/TheoryOfReddit/comments/8yg740/does_reddit_still_select_at_random_only_50_of/e2as9vr/

The app already lets you view the front page -- is that sufficient for what you're looking for?

**Comment by jayhybrid** [comment]
Yes, thank you!

**Comment by QuantumBadger** [comment]
Great :) I'll close this issue as the functionality already seems to be covered.
