### ISSUE TITLE
429 Too Many Requests should be handled appropriately rather than give a Error pop-up windows

### ISSUE THREAD

**Issue by Hanswanglin** [QuantumBadger/RedReader#643]
**Describe the problem**:
When you enter into any content list interface, like the following picture illustrates. There is function feature to **UpVote** or **DownVote** certain strip by the way of swiping left or right. However, if you do such operation with many times, the app will pop up a windows with the "429 Too Many Requests".

**How to reproduce**:
Open the application
Select any one of subscribed subreddits and go into
For any info-strip or article-strip, swipe left or swipe right for several times
The Error dialog comes forth 

**simple proposal**:
Maybe the app could handle this in the internal processing of manipulation

[screenshot]
![bug_finding](https://user-images.githubusercontent.com/25457920/50393753-4cb49200-0793-11e9-8b37-b655f044e1f8.png)
![error_detail](https://user-images.githubusercontent.com/25457920/50393759-53dba000-0793-11e9-8402-52f18fcc91dd.png)

**Comment by the10thWiz** [comment]
Should this cause an error message with more detail, or simply wait until it can send another request?

Implementing a better error message is probably the best way to deal with this issue. Rather than saying "Unknown reason," it should tell you that you're trying to send too many requests at a time and to try again later. Perhaps the error message could include a retry button?

**Comment by QuantumBadger** [comment]
Alpha 278 should show a better error message in these cases.
