### ISSUE TITLE
Animated gifs not animating

### ISSUE THREAD

**Issue by prof135** [QuantumBadger/RedReader#897]
Animated gifs not working in RedReader.?

See my post here: https://www.reddit.com/r/RedReader/comments/kzvuol/animated_gifs/

Reported 7mths ago via Reddit. Came across the bug again and thought I would post here.

Kind regards and thanks for the app.

**Comment by usr20210909** [comment]
GIFs in RedReader don't play for me since a very long time (multiple years?) on different phones, different versions of RedReader, Android versions and stock/custom ROMs. The weird thing is: they do play if they are part of an album but never when they are linked to directly like in this post.

My workaround is to configure the GIF viewer to use "External browser" so it opens and plays in Firefox/Opera/...

My current environment:

- Google Pixel 7
- Android 14 (February 5 security update - build number [UQ1A.240205.002](https://www.google.com/search?q=UQ1A.240205.002))
- RedReader v1.23.1 (installed from Google Play Store)

**Comment by knakamura8** [comment]
Have this same issue with inline gifs in a thread.

**Comment by QuantumBadger** [comment]
Should be fixed now in Alpha 353.
