### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by GNOMES** [QuantumBadger/RedReader#985]
App takes my credentials + 2FA, but returns to login screen on a fresh installation.

Happens on both internal and external browser. 

Ensured old approval was revoked from https://www.reddit.com/prefs/apps

Android 12

**Comment by QuantumBadger** [comment]
Thanks for reporting this, I can reproduce the issue as well. The issue is on Reddit's end, seeing as it happens even in an external browser. A couple of other Reddit apps have released updates to work around this. Still not sure why it's happening but I'll investigate.

As a temporary workaround, if you login to the Reddit site normally in the external browser, then go back to the app auth page and refresh the page, it seems to work for me.

**Comment by QuantumBadger** [comment]
I've put in a fix that seems to resolve this for me. It's in Alpha 312, please feel free to give it a go:

https://redreader.org/alpha/
