### ISSUE TITLE
"Custom Location" main menu item is missing when "Find Subreddit" is enabled

### ISSUE THREAD

**Issue by happysmash27** [QuantumBadger/RedReader#991]
In the newest update, "Custom Location" is replaced by the non-functional "Find Subreddit" menu (which just loads infinitely from what I see, but that's for another issue), unless "Find Subreddit" is disabled in the main menu options. **This can be worked around by disabling "Find Subreddit" in the main menu** (highlighted for anyone who wants usability back), but it would be nice to be able to have both options available.

**Comment by QuantumBadger** [comment]
When both options are enabled, "custom location" appears as an icon to the right of "find subreddit", and defaults to finding users.

I think the long loading times occur for people with an extremely long list of subscribed subreddits, and in a future version I'll link this up with the existing subscription database so that there's no loading time.
